export const StatsSection = () => {
  const stats = [
    { value: "30,000+", label: "Active Members" },
    { value: "$55M+", label: "Generated by Members" },
    { value: "5,000+", label: "Verified Wins" },
    { value: "24/7", label: "Real-Time Alerts" },
  ];

  return (
    <section className="py-16 sm:py-20 lg:py-24 bg-gradient-hero border-y border-border relative overflow-hidden">
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0 bg-gradient-to-r from-primary/20 via-transparent to-primary/20"></div>
      </div>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 sm:gap-8 lg:gap-12">
            {stats.map((stat, index) => (
              <div
                key={index}
                className="text-center space-y-2 sm:space-y-3 p-4 sm:p-6 rounded-xl bg-card/50 border border-border/50 backdrop-blur-sm hover:border-primary/50 hover:bg-card/80 transition-all duration-300 hover:scale-105"
              >
                <div className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-primary bg-gradient-primary bg-clip-text text-transparent leading-none">
                  {stat.value}
                </div>
                <div className="text-xs sm:text-sm text-muted-foreground uppercase tracking-wider font-medium leading-relaxed">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
